FROM payara/micro

COPY target/acmeair-customerservice-java-7.0.war ${DEPLOY_DIR}/

ENTRYPOINT ["java","-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=90.0", "-jar", "payara-micro.jar","--contextroot", "/customer","--port","9080"]
CMD ["--deploymentDir", "/opt/payara/deployments"]
